### ISSUE TITLE
Modal dialogs can cover menu buttons

### ISSUE THREAD

**Issue by phil-davis** [phil-davis/mautic#27]
For example, after pressing Apply a box pops up saying stuff like "Your account has been updated". That box stays for a second or 2. It can cover the "account" menu that has logout entry.

So we need to be more accommodating when trying to find and click stuff - repeat the attempt to click for some time, allowing the box to go away if it is there.

A typical exception was:
```
      WebDriver\Exception\UnknownError: unknown error: Element <a class="dropdown-toggle" data-toggle="dropdown" href="#">...</a> is not clickable at point (895, 30). Other element would receive the click: <div class="alert alert-growl">...</div>

        (Session info: chrome=61.0.3163.79)

        (Driver info: chromedriver=2.32.498550 (9dec58e66c31bcc53a9ce3c7226f0c1c5810906a),platform=Windows NT 10.0.10586 x86_64) in /home/travis/build/phil-davis/mautic/vendor/instaclick/php-webdriver/lib/WebDriver/Exception.php:155

      Stack trace:

      #0 /home/travis/build/phil-davis/mautic/vendor/instaclick/php-webdriver/lib/WebDriver/AbstractWebDriver.php(157): WebDriver\Exception::factory(13, 'unknown error: ...')

      #1 /home/travis/build/phil-davis/mautic/vendor/instaclick/php-webdriver/lib/WebDriver/AbstractWebDriver.php(218): WebDriver\AbstractWebDriver->curl('POST', '/click', NULL)

      #2 /home/travis/build/phil-davis/mautic/vendor/instaclick/php-webdriver/lib/WebDriver/Container.php(224): WebDriver\AbstractWebDriver->__call('click', Array)

      #3 /home/travis/build/phil-davis/mautic/vendor/behat/mink-selenium2-driver/src/Selenium2Driver.php(748): WebDriver\Container->__call('click', Array)

      #4 /home/travis/build/phil-davis/mautic/vendor/behat/mink-selenium2-driver/src/Selenium2Driver.php(742): Behat\Mink\Driver\Selenium2Driver->clickOnElement(Object(WebDriver\Element))

      #5 /home/travis/build/phil-davis/mautic/vendor/behat/mink/src/Element/NodeElement.php(153): Behat\Mink\Driver\Selenium2Driver->click('(//html//*[@id=...')

      #6 /home/travis/build/phil-davis/mautic/tests/ui/features/lib/NavTopbarPage.php(89): Behat\Mink\Element\NodeElement->click()

      #7 /tmp/ProxyManagerGeneratedProxy__PM__PageNavTopbarPageGeneratedb4553edecccbf81e715637e73b8dc5cf.php(34): Page\NavTopbarPage->selectNavTopbarMenuEntry('logout')

      #8 /home/travis/build/phil-davis/mautic/tests/ui/features/bootstrap/NavTopbarContext.php(35): ProxyManagerGeneratedProxy\__PM__\Page\NavTopbarPage\Generatedb4553edecccbf81e715637e73b8dc5cf->selectNavTopbarMenuEntry('logout')

      #9 [internal function]: NavTopbarContext->iLogout()
```

**Comment by phil-davis** [comment]
Fixed by #28
